---
collections:
  - name: hetzner.hcloud
    version: ">=6.7.0"
  - name: ansible.posix
    version: ">=2.1.0"
  - name: community.general
    version: ">=12.3.0"
  - name: amazon.aws
    version: ">=11.1.0"
  - name: community.aws
    version: ">=11.0.0"
  - name: community.crypto
    version: ">=3.1.0"
