---
collections:
  - name: hetzner.hcloud
    version: ">=4.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=8.0.0"
  - name: amazon.aws
    version: ">=8.0.0"
  - name: community.aws
    version: ">=8.0.0"
  - name: community.crypto
    version: ">=2.0.0"
